### ISSUE TITLE
Altitude should be in feet, not metres

### ISSUE THREAD

**Issue by texasyojimbo** [fsphil/ax25beacon#1]
I personally prefer SI units, and GPS NMEA reports altitude in meters. But the APRS specification says altitude should be reported in feet, not meters.

http://www.aprs.org/doc/APRS101.PDF

aprs.fi also seems to show altitudes in feet.

I am not sure if this is supposed to be above sea level or average terrain; the spec is silent on that issue, but the "antenna height" field is supposed to be feet above average terrain.

http://www.aprs.net/vm/DOS/PROTOCOL.HTM

I think we should have a switch for altitude unit conversion; if the switch is "on/true", then input will be in meters but output will be in feet. If switch is off, then data will pass-through without any unit conversion (presumably this will be for reporting in feet, or meters if you need to maintain backward compatibility).

**Comment by texasyojimbo** [comment]
Nevermind, after reviewing ax25beacon.c, I see that there is a conversion that takes place. 

I've forked this project, but I will probably just be writing new documentation, and maybe some stuff for base91 telemetry.

**Comment by fsphil** [comment]
No worries.

Yeah it doesn't explicitly state anywhere that it's converted, rather I treat it as just one more oddity required to implement APRS.

Some documentation would be appreciated, thanks for looking!
